# Generated by Django 4.1.5 on 2023-02-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front_Pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navs',
            name='seo_description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='navs',
            name='seo_keys',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='navs',
            name='seo_title',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
