# Generated by Django 4.1.5 on 2023-02-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front_Pages', '0002_navs_seo_description_navs_seo_keys_navs_seo_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='bg_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_mode', models.CharField(choices=[('prt', 'Portrait'), ('lnd', 'Landscape')], default='lnd', max_length=5)),
                ('bg_image', models.ImageField(upload_to='bg_image/front')),
            ],
        ),
    ]
