# Generated by Django 4.1.5 on 2023-02-17 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Front_Pages', '0008_skill_cat_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='description',
            new_name='proggress',
        ),
    ]
