# Generated by Django 4.1.5 on 2023-02-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front_Pages', '0011_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_info',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
