# Generated by Django 4.1.5 on 2023-02-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front_Pages', '0012_contact_info_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='smtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=100)),
                ('port', models.IntegerField(default=1)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=50)),
                ('receiver_mail', models.CharField(max_length=50)),
            ],
        ),
    ]
