# Generated by Django 4.1.5 on 2023-02-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front_Pages', '0013_smtp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtp',
            name='receiver_mail',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='smtp',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
