# Generated by Django 4.1.5 on 2023-03-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front_Pages', '0014_alter_smtp_receiver_mail_alter_smtp_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=35)),
                ('links', models.TextField(max_length=200)),
                ('logo_img', models.ImageField(upload_to='social_logo/front')),
            ],
        ),
        migrations.AlterField(
            model_name='social_id',
            name='links',
            field=models.TextField(max_length=200),
        ),
    ]
