# Generated by Django 4.1.5 on 2023-03-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front_Pages', '0015_market_alter_social_id_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_info',
            name='adresses',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='website',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='navs',
            name='nv_title',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='smtp',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='smtp',
            name='port',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='smtp',
            name='receiver_mail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='smtp',
            name='server',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='smtp',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
